# The world map to load
town: 'Town05'

# Weather and time of day settings
weather:
  # Values from -90 (midnight) to 90 (midday)
  sun_altitude_angle: 45.0  # Afternoon
  
  # 0-100 for all of these
  cloudiness: 30.0
  precipitation: 0.0        # No rain
  precipitation_deposits: 0.0 # No puddles
  wind_intensity: 10.0
  fog_density: 0.0

# The main vehicle we will be controlling
ego_vehicle:
  model: 'vehicle.tesla.model3'
  # List of sensors to attach. For now, just a camera.
  sensors:
    - type: 'sensor.camera.rgb'
      id: 'front_camera'
      transform: { x: 1.5, y: 0.0, z: 2.4 } # Position relative to car center
      attributes:
        image_size_x: 1280
        image_size_y: 720
        fov: 110
    - type: 'sensor.lidar.ray_cast'
      id: 'lidar'
      transform: { x: 0.0, y: 0.0, z: 2.4 }
      attributes:
        range: 80 # 80 meters
        channels: 32
        points_per_second: 320000
        rotation_frequency: 20
        upper_fov: 10
        lower_fov: -30

# Other actors in the scene
traffic:
  # Use CARLA's Traffic Manager for realistic behavior
  use_traffic_manager: true
  
  # Number of other vehicles to spawn
  num_vehicles: 50
  
  # Number of pedestrians to spawn
  num_pedestrians: 40
  
  # A seed for the random number generator to make traffic reproducible
  seed: 42 